### PR TITLE
added appbar, login dialog styling, fixed homepage linking with node.…

### PR DESCRIPTION
**Pull request by YMari**
…js link instead of material-ui, added _document and _app file, added theme, fixed package.json dependencies for material-ui

### CODE REVIEW

**Comment by YMari** [comment]
login dialog needs styling but its being annoying with centering 😔

**Comment by kenneth-rosario** [comment]
Se ve ready!!

**Review by kenneth-rosario — APPROVED** [review]
Se ve ready todo

**Comment by kenneth-rosario** [comment]
Cuando estes set dale merge :D

**Pull request merged**
